np.swapaxes()

In [1]:
import numpy as np

x = np.array([[7, 8,9]])
x

array([[7, 8, 9]])

In [3]:
y= np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [4]:
y[0,0] = 10
x

array([[10,  8,  9]])

In [5]:
x = np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [7]:
np.transpose(x,(2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

view & copy

In [9]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [10]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [11]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [12]:
v[2]=200
v

array([  0,   1, 200,   3,   4])

In [13]:
org

array([  0,   1, 200,   3,   4])

In [14]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [15]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [18]:
c[2] =200
c

array([  0,   1, 200,   3,   4])

In [19]:
org

array([0, 1, 2, 3, 4])

ndarray.base

In [20]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [21]:
y=x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
y.base

array([0, 1, 2, 3, 4, 5])

In [23]:
print(x.base)

None


In [24]:
z=y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [25]:
c=z.copy()
print(c.base)

None


In [26]:
lst=list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [27]:
lst[3:5] = [30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [28]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
x[3:5]=[30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [30]:
#오류 발생
x[3:5] = [30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b = a
b is a

True

In [33]:
print(id(a))
print(id(b))

137406374545040
137406374545040


In [34]:
print(b.base)

None


In [36]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [37]:
v=a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [38]:
print(id(a))
print(id(v))

137406374545040
137406374639056


In [39]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [40]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

브로드캐스팅

In [41]:
a = np.array([3,4,5])
b = np.array([8,7,6])
a+b

array([11, 11, 11])

In [42]:
#오류 발생
a = np.array([3,4,5,7])
b= np.array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [44]:
from numpy import array
a = array([3,4,5])
a

array([3, 4, 5])

In [45]:
import numpy as np

a = np.array([3,4,5])
a

array([3, 4, 5])

In [46]:
b=2
b

2

In [47]:
a +b

array([5, 6, 7])

In [48]:
from numpy import array

A = array([[1,2,3],[1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [49]:
A+2

array([[3, 4, 5],
       [3, 4, 5]])

In [50]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
y = arange(-1,2)
y

array([-1,  0,  1])

In [52]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [53]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [54]:
from numpy import arange
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [57]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [58]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [59]:
from numpy import arange

x=arange(1,4)
x

array([1, 2, 3])

In [60]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [61]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [62]:
x-y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [63]:
from numpy import arange

x=arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [64]:
y=arange(1,3)
y

array([1, 2])

In [65]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [66]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [68]:
from numpy import array2string
x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [70]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [72]:
a= x[np.newaxis,:]
a

array([[ 0, 10, 20, 30]])

In [73]:
from numpy import array2string
b = array([1,2,3])
b

array([1, 2, 3])

In [79]:
x = arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [81]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [82]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [83]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [84]:
#오류
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [85]:
from numpy import arange
x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [86]:
x[0,1]

1

In [87]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [88]:
x[,2:8]
#오류

SyntaxError: invalid syntax (<ipython-input-88-27d308b48cc4>, line 1)

In [89]:
x[[0],[1]]

array([1])

In [91]:
x[:,[5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [92]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [93]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [94]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [95]:
x[[1,3],[2,2]]

array([10, 26])

In [96]:
x[[1,3],[2]]

array([10, 26])

In [97]:
x[[1,3],2]

array([10, 26])

In [98]:
x[[1,3],[3,3]]

array([11, 27])

In [99]:
x[[1,3],[3]]

array([11, 27])

In [101]:
from numpy import array

x[array([0,2,4]), array([0,1])]

# 오류

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [102]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [103]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [105]:
x[np.array([0,2,4]),:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

2교시

In [106]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [107]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [108]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [109]:
c = np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [110]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [111]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [112]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [113]:
d = np.array([100,200,300])
np.vstack((a,d))

#오류

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [115]:
import numpy as np

x=np.array([1,2,3])
y=np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [116]:
np.r_[a,b,c]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [117]:
import numpy as np

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [118]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [119]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [120]:
np.c_[a,b]

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [122]:
c=np.array([[10,20],[30,40]])
c

array([[10, 20],
       [30, 40]])

In [124]:
#error
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [125]:
np.hstack((np.arange(3),np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [126]:
np.r_[np.arange(3),np.arange(10,15)]

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [127]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [128]:
b=np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [129]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [130]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [131]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [132]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [133]:
y[:,np.newaxis]

array([[10],
       [20],
       [30]])

In [134]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [135]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [136]:
np.column_stack == np.hstack

False

In [137]:
import numpy as np

a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [141]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [142]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [143]:
a=np.array([4.,2.,1.])
b=np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [144]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [145]:
np.row_stack == np.vstack

True

In [146]:
import numpy as np

a = np.array([1,2])
b= np.array([3,4])
c = np.array([5,6])

In [147]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [148]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [149]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [150]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [157]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [152]:
z=np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [158]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [154]:
#error

np.concatenate((x,y,z))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [159]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [160]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [161]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [162]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [163]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [164]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [166]:
np.stack((a,b),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [170]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [167]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [169]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [171]:
ax0 = np.stack((x,y,z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [172]:
ax0.shape

(3, 2, 3)

In [173]:
ax1 = np.stack((x,y,z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [174]:
ax0.shape

(3, 2, 3)

In [175]:
ax2 = np.stack((x,y,z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [176]:
ax0.shape

(3, 2, 3)

In [177]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [178]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [179]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [180]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [181]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [182]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [184]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [185]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [186]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [187]:
c =np.arange(1,6,2)
c

array([1, 3, 5])

In [188]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [189]:
np.hstack((a,c[:,np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [190]:
np.hstack((a,c))

#error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [191]:
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [192]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [193]:
np.c_[a,c]

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [194]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [196]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [197]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [198]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [199]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [200]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [201]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [202]:
x=np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [203]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [204]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [205]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [207]:
np.column_stack[x, 10, 20,y]

TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [208]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [209]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [210]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [211]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [212]:
np.r_[3:10:3, [0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [213]:
np.r_[-1:1:6j, [0]*2, 5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [214]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [215]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [216]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [217]:
np.r_['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [218]:
np.r_['-1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [219]:
np.r_['1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [220]:
np.r_['0,2',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
np.r_['0,3',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [223]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [230]:
np.r_['0,3,0',[1,2,3],[4,5,6]].shape

(6, 1, 1)

In [232]:
np.r_['0,3,1',[1,2,3],[4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [233]:
print(np.expand_dims(np.array([1,2,3]), axis=(0,2)))
print(np.expand_dims(np.array([4,5,6]), axis=(0,2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [235]:
np.r_['0,3,2',[1,2,3],[4,5,6]].shape

(2, 1, 3)

In [236]:
print(np.r_[[1,2,3],[4,5,6]])

np.r_['r',[1,2,3],[4,5,6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [237]:
print(np.r_[[1,2,3],[4,5,6]])
np.r_['c', [1,2,3],[4,5,6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [238]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [239]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [240]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [241]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [242]:
import numpy as np

a = np.array([1,2,3])
b= np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [243]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [244]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [245]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
np.concatenate((a[np.newaxis,:], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [248]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [249]:
np.hstack((a[:, np.newaxis], b[:,np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [250]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [251]:
np.concatenate(((a[:,np.newaxis], b[:,np.newaxis])),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [252]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

In [253]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [254]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [255]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [256]:
np.split(x, 4)

#error

ValueError: array split does not result in an equal division

In [257]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [258]:
np.split(x, [2,6])
[array([1,2]),array([3,4,5,6]),array([7,8,9])]

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [259]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [260]:
np.split(y,[2,3,4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [261]:
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [262]:
y[4:6]

array([50, 60])

In [264]:
y[6:]

array([], dtype=int64)

In [266]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [267]:
np.split(a,3,axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [268]:
np.split(a,4,axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [269]:
np.split(a,5,axis=1)
#error

ValueError: array split does not result in an equal division

In [270]:
np.split(a,[3,5,7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [271]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [272]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [274]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [275]:
np.hsplit(a,[2,5])

[array([[ 0,  1],
        [12, 13]]),
 array([[ 2,  3,  4],
        [14, 15, 16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11],
        [17, 18, 19, 20, 21, 22, 23]])]

In [278]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [279]:
np.vsplit(a,2)
#error

ValueError: vsplit only works on arrays of 2 or more dimensions

In [280]:
a = np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [281]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [282]:
np.vsplit(a,(1,4,6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [283]:
a[:1, :]

array([[0, 1, 2]])

In [284]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [285]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [286]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [287]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [289]:
np.split(x,2,axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [288]:
x[:,:2,:]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]])

In [290]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [291]:
np.hsplit(x,[1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [292]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [293]:
np.vsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [294]:
np.split(x,2,axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [295]:
x[:2,:,:]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [296]:
import numpy as np

x=np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [297]:
np.array_split(x,2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [298]:
np.array_split(x,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [299]:
np.array_split(x,4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [300]:
np.array_split(x,5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [301]:
np.array_split(x,[2,4,8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [302]:
import numpy as np

a =np.arange(35).reshape(7,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [303]:
np.array_split(a,2,axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [304]:
np.array_split(a,2,axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [305]:
np.array_split(a,4,axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [306]:
np.array_split(a,4,axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [307]:
np.array_split(a,[2,4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [308]:
np.array_split(a,[2,4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [314]:
import numpy as np

x = np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [316]:
np.dsplit(x,2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [318]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7CF86A2B9000

In [319]:
r = rg.random()
r

0.22733602246716966

In [320]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [321]:
rg.random((4,3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [322]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0,high=10,size=3)
r

array([6, 2, 7])