numpy 개요와 자료형 ndarray

In [15]:
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |

In [8]:
import numpy as np

a = np.ndarray(shape=(2,2), dtype=int)
a

array([[     95417231715607,                   0],
       [    139633681760255, 4998714628501696105]])

In [9]:
import numpy as np

a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [12]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [14]:
import numpy as np

np.arrary(1,2,3)

#수를 나열하면 오류 발생

AttributeError: module 'numpy' has no attribute 'arrary'

In [16]:
import numpy as np

a = np.ndarray((2,3))
a

array([[4.71423842e-310, 0.00000000e+000, 6.89883872e-310],
       [6.89883869e-310, 6.89883872e-310, 6.89883866e-310]])

In [17]:
import numpy as np

a = np.ndarray((3,2), dtype=int)
a

array([[ 95417247957839,               0],
       [139634050138480, 139634049695792],
       [139634050142704, 139634049085104]])

In [18]:
a = np.ndarray((3,2), dtype=int)
a

array([[ 95417246918809,               0],
       [139634049701360, 139634049701424],
       [139634049701488, 139634049701616]])

In [20]:
np.ndarray?

In [21]:
import numpy as np

a = np.ndarray(shape=(2,2), dtype=int)
a

array([[139607642560638,               0],
       [              0,               0]])

In [22]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)

(2, 2)
2
4
8
int64
32


In [23]:
a.data

In [24]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [25]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(dtype, align=False, copy=False, [metadata])
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  dtype
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  metadata : dict, optional
 |      An optional dictionary with dtyp

array()

In [26]:
import numpy as np

a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [27]:
type(a)

numpy.ndarray

In [28]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [29]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [30]:
np.array(1,2,3) #오류(리스트로 작성해야함)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [31]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [33]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사아자'],dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [34]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'],dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [35]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'],dtype='<U64')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마', '라마바', '사아자'], dtype='<U64')

In [36]:
lang = np.array(['파이썬','자바','씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [37]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [38]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

np.array()

In [40]:
import numpy as np

print(np.arange(3)) # >> (0,3,1)
print(np.arange(3,7)) # >> (3,7,1)
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [41]:
import numpy as np

print(np.arange(2.0)) # (0.0, 2.0, 1.0)
print(np.arange(2.0, 6.5)) #(2.0, 6.5, 1.0)
print(np.arange(2.0, 6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [44]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [45]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

np.reshape()

In [46]:
import numpy as np

a = np.arange(12).reshape(3, 5) #오류
a

ValueError: cannot reshape array of size 12 into shape (3,5)

In [47]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
np.reshape(a, (2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [49]:
np.reshape(a, (3,5)) #오류

ValueError: cannot reshape array of size 12 into shape (3,5)

In [50]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.reshape(b, (2,-1)) # np.reshape(b, (2,3))

#np.reshape(b, (5,-1)) # 오류

#np.reshape(b, (6,-1)) # np.reshape(b, (6,1))

array([[1, 2, 3],
       [4, 5, 6]])

np.linspace

In [55]:
import numpy as np

np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [56]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [57]:
print( (3-2) / (50-1))

0.02040816326530612


In [58]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [60]:
print((3-2) / 50)

0.02


In [61]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [62]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

arange()의 문제:float 수의 문제

In [63]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [64]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [65]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [66]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

zeros()와 ones()

In [67]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [68]:
a.dtype

dtype('float64')

In [69]:
np.zeros?

In [70]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [71]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [72]:
b.shape

(2, 1)

In [73]:
import numpy as np

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

np.eye()

In [75]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [77]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [79]:
a = np.eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
a = np.eye(3,4,-1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

full() empty()

In [85]:
import numpy as np

np.full([2,3],50)

array([[50, 50, 50],
       [50, 50, 50]])

In [82]:
np.full([2,3], (1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [86]:
np.full([2,3], (1,2)) #오류 (갯수가 달라서)

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [83]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [87]:
np.full([4,3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [88]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [93]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [94]:
np.empty([2,3], dtype=int)

array([[     95427955658351,                   0,        416611827826],
       [       442381631598, 3203025183010979941, 7307218078150255136]])

In [96]:
np.empty((3, 2, 3),int)

array([[[139614032960390,               0, 139632763455888],
        [139632763457408, 139632763456448, 139634049695792]],

       [[139632763428560, 139634049695792, 139632763415280],
        [139632763252208, 139632763416912, 139632763252272]],

       [[139632763252272, 139634049695792, 139634049695792],
        [             33,  95440127439136, 139634055974128]]])

In [89]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [90]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [91]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [92]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [104]:
import numpy as np

np.full_like(a, range(4))

ValueError: could not broadcast input array from shape (4,) into shape (3,)

배열 연산

In [97]:
a = np.arange(3)
a

array([0, 1, 2])

In [98]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [106]:
import numpy as np

a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
b = np.full_like(a, [1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [108]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [109]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [111]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [112]:
a += b #오류

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [114]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [115]:
a = np.full((2,3),[1,2,3]) #행렬 계산
a

array([[1, 2, 3],
       [1, 2, 3]])

In [116]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [126]:
a @ b #곱셈

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [118]:
a.dot(b) #곱셈

array([[12,  6],
       [12,  6]])

In [124]:
b.dot(a)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [127]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [119]:
a = np.array([[10, 20], [5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [120]:
a.sum()

46

In [121]:
a.sum(axis=0)

array([16, 30])

In [122]:
a.sum(axis=1)

array([30, 13,  3])

In [128]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [129]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [130]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [131]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [132]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [133]:
import numpy as np

a = np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

In [134]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [135]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [136]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [139]:
np.add(a,b)

array([ 3,  6, 11])

In [141]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [140]:
np.power(a,b)

array([ 1, 16, 81])

배열 슬라이싱과 형태 수정

In [148]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [143]:
print(a[3])
print(a[-2])

9
64


In [144]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [145]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [147]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [149]:
a[::-2]

array([81, 49, 25,  9,  1])

In [150]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [152]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [153]:
a[2:5] = [-5, -5] #오류
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [154]:
b= np.array([5]*10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [155]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [157]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [159]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [160]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [161]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [162]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [163]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [164]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [165]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [166]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [167]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [168]:
a[2,4]

16

In [169]:
a[2][4]

16

In [170]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [171]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [172]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [174]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [175]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [176]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [177]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [178]:
a[:, 1, 1]

array([ 5, 17])

In [179]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [180]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [181]:
a[1, ..., 1]

array([13, 17, 21])

In [182]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
a= np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [186]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [229]:
b[0]= 100
b

array([[[100, 100],
        [100, 100]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]]])

In [230]:
a

array([[1, 2, 3],
       [4, 5, 6]])

np.transpose()

In [187]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [190]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [193]:
np.transpose(a, (0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
np.transpose(a, (1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [195]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [196]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [198]:
np.transpose(b, (0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [199]:
np.transpose(b, (2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [200]:
np.transpose(b, (0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [202]:
c = np.arange(1,13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [203]:
c.transpose((1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [204]:
np.transpose(c, (1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [205]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [206]:
x = np.array([[7,8,9]])
x

array([[7, 8, 9]])

In [207]:
y = np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [208]:
y[0,0]=10
x

array([[10,  8,  9]])

In [210]:
x = np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [211]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [212]:
np.transpose(x, (2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [213]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [214]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [215]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [216]:
org

array([  0,   1, 200,   3,   4])

In [218]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [219]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [221]:
c[2] =200
c

array([  0,   1, 200,   3,   4])

In [222]:
org

array([0, 1, 2, 3, 4])

In [223]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [225]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [226]:
y.base

array([0, 1, 2, 3, 4, 5])

In [228]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [231]:
c = z.copy()
print(c.base)

None


In [233]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [234]:
lst[3:5] = [30, 40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [235]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [236]:
x[3:5] = [30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [237]:
x[3:5] = [30,40,50]  #오류
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [238]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [239]:
b = a
b is a

True

In [240]:
print(id(a))
print(id(b))

139632733322192
139632733322192


In [241]:
print(b.base)

None


In [242]:
b[0,0]= 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [243]:
v = a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [244]:
print(id(a))
print(id(v))

139632733322192
139632733322288


In [245]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

---- p.126